server:
  port: 80

eureka:
  client:
    register-with-eureka: true  #注册到eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#开启feign支持hystrix
feign:
  hystrix:
    enabled: true
